library(dmetar)
library(meta)
library(esc)
library(tidyverse)
library(openxlsx)
library(metafor)
library(dbplyr)

df.cont <- read.xlsx("cont-data.xlsx")
df.bin <- read.xlsx("bin-data.xlsx")
df.dem <- read.xlsx("dem-data.xlsx")

df.cont <- left_join(df.cont, df.dem, by = "author")
df.bin <- left_join(df.bin, df.dem, by = "author")

df.reintubation <- df.bin %>% filter(outcome == "reintubation")
df.pneumonia <- df.bin %>% filter(outcome == "pneumonia")
df.atelectasis <- df.bin %>% filter(outcome == "atelectasis")
df.hypoxemia <- df.bin %>% filter(outcome == "hypoxemia")
df.mortality <- df.bin %>% filter(outcome == "mortality")
df.toniv <- df.bin %>% filter(outcome == "toniv")
df.ppc <- df.bin %>% filter(outcome == "ppc")

df.hlos <- df.cont %>% filter(outcome =="hlos")
df.iculos <- df.cont %>% filter(outcome =="iculos")
df.discomfort <- df.cont %>% filter(outcome =="discomfort")
df.pfr2h <- df.cont %>% filter(outcome =="pfr2h")
df.paco2early <- df.cont %>% filter(outcome =="paco2early")
df.pao2early <- df.cont %>% filter(outcome =="pao2early")
df.phearly <- df.cont %>% filter(outcome =="phearly")
df.rrearly <- df.cont %>% filter(outcome =="rrearly")
df.spoearly <- df.cont %>% filter(outcome =="spoearly")
df.hrearly <- df.cont %>% filter(outcome =="hrearly")
df.map <- df.cont %>% filter(outcome =="map")

